### ISSUE TITLE
partially populated FilterView causes crash

### ISSUE THREAD

**Issue by fire-eggs** [fire-eggs/Danbooru2019#47]
Inadvertently set up my FilterView as follows:

```
     touhou
AND
AND  translated
```

Crashed.

**Comment by fire-eggs** [comment]
```
    touhou

AND translated
```
(note the middle entry is fully empty)
```
select image_id from images where is_deleted=0 and is_banned=0 and image_id in (select image_id from imageTags where tag_id in (select tag_id from tags where name like ?) INTERSECT select image_id from imageTags where tag_id in (select tag_id from tags where name like ?)) order by image_id
('touhou',)
Exception ignored in thread started by: <function producer at 0x7f37b51811b0>
Traceback (most recent call last):
  File "/home/kevin/db2020/db2024_meta/browser/./tagview.py", line 291, in producer
    image_ids = DanbooruDB().getImagesForTags2(postsFilter.TagFilter1(), \
  File "/home/kevin/db2020/db2024_meta/browser/danboorudb.py", line 169, in getImagesForTags2
    self.cur.execute(full,params)
sqlite3.ProgrammingError: Incorrect number of bindings supplied. The current statement uses 2, and there are 1 supplied.
```

**Comment by fire-eggs** [comment]
Fixed. Includes a fix for the observed issue where the first clause being empty would cause problems.
