### ISSUE TITLE
if close sub-window, can't close main window

### ISSUE THREAD

**Issue by fire-eggs** [fire-eggs/Danbooru2019#59]
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.10/tkinter/__init__.py", line 1921, in __call__
    return self.func(*args)
  File "/home/kevin/db2020/db2024_meta/browser/./tagview.py", line 377, in onClose
    print(filterClass.master.winfo_geometry())
  File "/usr/lib/python3.10/tkinter/__init__.py", line 1122, in winfo_geometry
    return self.tk.call('winfo', 'geometry', self._w)
_tkinter.TclError: bad window path name ".!toplevel"
```

**Comment by fire-eggs** [comment]
Handled exception. The lack of memory for window positions/sizes is a problem.
